// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            Name = "Camiseta Básica",
                            Price = 29900m,
                            SKU = "CAMBAS001",
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            Name = "Jean Slim",
                            Price = 89900m,
                            SKU = "JEASLM002",
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            Category = 2,
                            Name = "Vestido Floral",
                            Price = 65900m,
                            SKU = "VESFLO003",
                            Stock = 20
                        },
                        new
                        {
                            Id = 4,
                            Category = 3,
                            Name = "Chaqueta Denim",
                            Price = 120000m,
                            SKU = "CHADEN004",
                            Stock = 15
                        },
                        new
                        {
                            Id = 5,
                            Category = 4,
                            Name = "Blusa Manga Larga",
                            Price = 45900m,
                            SKU = "BLUMAN005",
                            Stock = 40
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
